version: '3.8'

services:
  siswebbotica:
    image: ${DOCKER_REGISTRY-}siswebbotica
    build:
      context: .
      dockerfile: SISWEBBOTICA/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__CadenaSQL=Server=sql-server-db,1433;Database=SisfarmaciaDB;User Id=sa;Password=tuContrasenaFuerte123!;TrustServerCertificate=True;
    depends_on:
      - sql-server-db

  sql-server-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=tuContrasenaFuerte123! # ¡Añadí un '!' para que sea más segura
    ports:
      - "1433:1433"